/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiger_airline;

/**
 *
 * @author SHEHANKA
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lblLoginImg = new javax.swing.JLabel();
        lblCallNow = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblLogoText = new javax.swing.JLabel();
        panelTabbed = new javax.swing.JTabbedPane();
        panelFlight = new javax.swing.JPanel();
        lblFlightText = new javax.swing.JLabel();
        PanelTabbedD_I = new javax.swing.JTabbedPane();
        panelDomestic = new javax.swing.JPanel();
        radioOneWay = new javax.swing.JRadioButton();
        radioRoundTrip = new javax.swing.JRadioButton();
        radioMultiCity = new javax.swing.JRadioButton();
        tfieldFrom = new javax.swing.JTextField();
        lblFrom = new javax.swing.JLabel();
        tfieldTo = new javax.swing.JTextField();
        lblTo = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        lblDeparture = new javax.swing.JLabel();
        tfieldDate = new javax.swing.JTextField();
        lblReturn = new javax.swing.JLabel();
        tfieldDate1 = new javax.swing.JTextField();
        lblChild = new javax.swing.JLabel();
        lblAdults1 = new javax.swing.JLabel();
        lblChild1 = new javax.swing.JLabel();
        tfieldAdults = new javax.swing.JTextField();
        tfieldChilds = new javax.swing.JTextField();
        tfieldsInfants = new javax.swing.JTextField();
        lblClass = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblFlight_Hotel = new javax.swing.JLabel();
        lblSearchFlight = new javax.swing.JLabel();
        panelInternational = new javax.swing.JPanel();
        radioOneWay1 = new javax.swing.JRadioButton();
        radioRoundTrip1 = new javax.swing.JRadioButton();
        radioMultiCity1 = new javax.swing.JRadioButton();
        tfieldFrom1 = new javax.swing.JTextField();
        lblFrom1 = new javax.swing.JLabel();
        tfieldTo1 = new javax.swing.JTextField();
        lblTo1 = new javax.swing.JLabel();
        separator2 = new javax.swing.JSeparator();
        lblDeparture1 = new javax.swing.JLabel();
        tfieldDate2 = new javax.swing.JTextField();
        lblReturn1 = new javax.swing.JLabel();
        tfieldDate3 = new javax.swing.JTextField();
        lblChild2 = new javax.swing.JLabel();
        lblAdults2 = new javax.swing.JLabel();
        lblChild3 = new javax.swing.JLabel();
        tfieldAdults1 = new javax.swing.JTextField();
        tfieldChilds1 = new javax.swing.JTextField();
        tfieldsInfants1 = new javax.swing.JTextField();
        lblClass1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        lblFlight_Hotel1 = new javax.swing.JLabel();
        lblSearchFlight1 = new javax.swing.JLabel();
        panelHotel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblFlight_Hotel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));
        panelBackground.setPreferredSize(new java.awt.Dimension(1366, 768));
        panelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(52, 152, 219));

        lblLoginImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiger_airline/img/ImgLogin.jpg"))); // NOI18N

        lblCallNow.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblCallNow.setForeground(new java.awt.Color(255, 255, 255));
        lblCallNow.setText("Login/Register");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiger_airline/img/ImgLogo.jpg"))); // NOI18N

        lblLogoText.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblLogoText.setForeground(new java.awt.Color(255, 255, 255));
        lblLogoText.setText("IGER Airline");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogoText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1023, Short.MAX_VALUE)
                .addComponent(lblLoginImg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCallNow, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogoText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblLoginImg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCallNow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelBackground.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 50));

        panelTabbed.setBackground(new java.awt.Color(25, 191, 254));
        panelTabbed.setForeground(new java.awt.Color(25, 191, 254));
        panelTabbed.setOpaque(true);

        panelFlight.setOpaque(false);

        lblFlightText.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        lblFlightText.setForeground(new java.awt.Color(255, 255, 255));
        lblFlightText.setText("Book Domestic & International Flight Tickets");

        panelDomestic.setOpaque(false);

        radioOneWay.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        radioOneWay.setForeground(new java.awt.Color(255, 255, 255));
        radioOneWay.setText("One Way");
        radioOneWay.setOpaque(false);

        radioRoundTrip.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        radioRoundTrip.setForeground(new java.awt.Color(255, 255, 255));
        radioRoundTrip.setText("Round Trip");
        radioRoundTrip.setOpaque(false);

        radioMultiCity.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        radioMultiCity.setForeground(new java.awt.Color(255, 255, 255));
        radioMultiCity.setText("Multi City");
        radioMultiCity.setOpaque(false);
        radioMultiCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMultiCityActionPerformed(evt);
            }
        });

        tfieldFrom.setBackground(new java.awt.Color(255, 255, 255));
        tfieldFrom.setText("Type Departure City");
        tfieldFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldFromActionPerformed(evt);
            }
        });

        lblFrom.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblFrom.setForeground(new java.awt.Color(255, 255, 255));
        lblFrom.setText("FROM");

        tfieldTo.setBackground(new java.awt.Color(255, 255, 255));
        tfieldTo.setText("Type Destination City");
        tfieldTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldToActionPerformed(evt);
            }
        });

        lblTo.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTo.setForeground(new java.awt.Color(255, 255, 255));
        lblTo.setText("TO");

        lblDeparture.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblDeparture.setForeground(new java.awt.Color(255, 255, 255));
        lblDeparture.setText("Deparure");

        tfieldDate.setBackground(new java.awt.Color(255, 255, 255));
        tfieldDate.setText("Type Date");

        lblReturn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblReturn.setForeground(new java.awt.Color(255, 255, 255));
        lblReturn.setText("Return");

        tfieldDate1.setBackground(new java.awt.Color(255, 255, 255));
        tfieldDate1.setText("Type Date");

        lblChild.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblChild.setForeground(new java.awt.Color(255, 255, 255));
        lblChild.setText("CHILDS:(2-11 YRS)");

        lblAdults1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblAdults1.setForeground(new java.awt.Color(255, 255, 255));
        lblAdults1.setText("ADULTS:(12+ YRS)");

        lblChild1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblChild1.setForeground(new java.awt.Color(255, 255, 255));
        lblChild1.setText("INFANTS:(0-2 YRS)");

        tfieldAdults.setBackground(new java.awt.Color(255, 255, 255));
        tfieldAdults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldAdultsActionPerformed(evt);
            }
        });

        tfieldChilds.setBackground(new java.awt.Color(255, 255, 255));

        tfieldsInfants.setBackground(new java.awt.Color(255, 255, 255));

        lblClass.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblClass.setForeground(new java.awt.Color(255, 255, 255));
        lblClass.setText("CLASS:");

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economy", "Premium Economy", "Business" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        lblFlight_Hotel.setBackground(new java.awt.Color(191, 191, 191));
        lblFlight_Hotel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblFlight_Hotel.setForeground(new java.awt.Color(255, 255, 255));
        lblFlight_Hotel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFlight_Hotel.setText("Flight + Hotel");
        lblFlight_Hotel.setOpaque(true);

        lblSearchFlight.setBackground(new java.awt.Color(255, 255, 255));
        lblSearchFlight.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblSearchFlight.setForeground(new java.awt.Color(25, 191, 254));
        lblSearchFlight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearchFlight.setText("Search Flight");
        lblSearchFlight.setOpaque(true);

        javax.swing.GroupLayout panelDomesticLayout = new javax.swing.GroupLayout(panelDomestic);
        panelDomestic.setLayout(panelDomesticLayout);
        panelDomesticLayout.setHorizontalGroup(
            panelDomesticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDomesticLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelDomesticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDomesticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelDomesticLayout.createSequentialGroup()
                            .addComponent(radioOneWay)
                            .addGap(91, 91, 91)
                            .addComponent(radioRoundTrip)
                            .addGap(87, 87, 87)
                            .addComponent(radioMultiCity))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDomesticLayout.createSequentialGroup()
                            .addGroup(panelDomesticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelDomesticLayout.createSequentialGroup()
                                    .addComponent(lblFrom)
                                    .addGap(280, 280, 280)
                                    .addComponent(lblTo))
                                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelDomesticLayout.createSequentialGroup()
                                    .addGroup(panelDomesticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblDeparture))
                                    .addGap(36, 36, 36)
                                    .addGroup(panelDomesticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblReturn)
                                        .addComponent(tfieldDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(76, 76, 76)
                                    .addGroup(panelDomesticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblAdults1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfieldAdults)))
                                .addComponent(lblClass)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelDomesticLayout.createSequentialGroup()
                                    .addComponent(lblSearchFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(lblFlight_Hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(55, 55, 55))
                        .addGroup(panelDomesticLayout.createSequentialGroup()
                            .addComponent(tfieldFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(135, 135, 135)
                            .addComponent(tfieldTo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDomesticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfieldChilds, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblChild)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(panelDomesticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblChild1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfieldsInfants))
                .addGap(82, 82, 82))
        );
        panelDomesticLayout.setVerticalGroup(
            panelDomesticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDomesticLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelDomesticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioOneWay)
                    .addComponent(radioRoundTrip)
                    .addComponent(radioMultiCity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDomesticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFrom)
                    .addComponent(lblTo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDomesticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfieldFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDomesticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDomesticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDeparture)
                        .addComponent(lblReturn))
                    .addComponent(lblAdults1)
                    .addGroup(panelDomesticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblChild)
                        .addComponent(lblChild1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDomesticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldAdults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldChilds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldsInfants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(panelDomesticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFlight_Hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        PanelTabbedD_I.addTab("Domestic", panelDomestic);

        radioOneWay1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        radioOneWay1.setForeground(new java.awt.Color(255, 255, 255));
        radioOneWay1.setText("One Way");
        radioOneWay1.setOpaque(false);

        radioRoundTrip1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        radioRoundTrip1.setForeground(new java.awt.Color(255, 255, 255));
        radioRoundTrip1.setText("Round Trip");
        radioRoundTrip1.setOpaque(false);

        radioMultiCity1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        radioMultiCity1.setForeground(new java.awt.Color(255, 255, 255));
        radioMultiCity1.setText("Multi City");
        radioMultiCity1.setOpaque(false);
        radioMultiCity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMultiCity1ActionPerformed(evt);
            }
        });

        tfieldFrom1.setBackground(new java.awt.Color(255, 255, 255));
        tfieldFrom1.setText("Type Departure City");
        tfieldFrom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldFrom1ActionPerformed(evt);
            }
        });

        lblFrom1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblFrom1.setForeground(new java.awt.Color(255, 255, 255));
        lblFrom1.setText("FROM");

        tfieldTo1.setBackground(new java.awt.Color(255, 255, 255));
        tfieldTo1.setText("Type Destination City");
        tfieldTo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldTo1ActionPerformed(evt);
            }
        });

        lblTo1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTo1.setForeground(new java.awt.Color(255, 255, 255));
        lblTo1.setText("TO");

        lblDeparture1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblDeparture1.setForeground(new java.awt.Color(255, 255, 255));
        lblDeparture1.setText("Deparure");

        tfieldDate2.setBackground(new java.awt.Color(255, 255, 255));
        tfieldDate2.setText("Type Date");

        lblReturn1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblReturn1.setForeground(new java.awt.Color(255, 255, 255));
        lblReturn1.setText("Return");

        tfieldDate3.setBackground(new java.awt.Color(255, 255, 255));
        tfieldDate3.setText("Type Date");

        lblChild2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblChild2.setForeground(new java.awt.Color(255, 255, 255));
        lblChild2.setText("CHILDS:(2-11 YRS)");

        lblAdults2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblAdults2.setForeground(new java.awt.Color(255, 255, 255));
        lblAdults2.setText("ADULTS:(12+ YRS)");

        lblChild3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblChild3.setForeground(new java.awt.Color(255, 255, 255));
        lblChild3.setText("INFANTS:(0-2 YRS)");

        tfieldAdults1.setBackground(new java.awt.Color(255, 255, 255));
        tfieldAdults1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfieldAdults1ActionPerformed(evt);
            }
        });

        tfieldChilds1.setBackground(new java.awt.Color(255, 255, 255));

        tfieldsInfants1.setBackground(new java.awt.Color(255, 255, 255));

        lblClass1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblClass1.setForeground(new java.awt.Color(255, 255, 255));
        lblClass1.setText("CLASS:");

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economy", "Premium Economy", "Business" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        lblFlight_Hotel1.setBackground(new java.awt.Color(191, 191, 191));
        lblFlight_Hotel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblFlight_Hotel1.setForeground(new java.awt.Color(255, 255, 255));
        lblFlight_Hotel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFlight_Hotel1.setText("Flight + Hotel");
        lblFlight_Hotel1.setOpaque(true);

        lblSearchFlight1.setBackground(new java.awt.Color(255, 255, 255));
        lblSearchFlight1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblSearchFlight1.setForeground(new java.awt.Color(25, 191, 254));
        lblSearchFlight1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearchFlight1.setText("Search Flight");
        lblSearchFlight1.setOpaque(true);

        javax.swing.GroupLayout panelInternationalLayout = new javax.swing.GroupLayout(panelInternational);
        panelInternational.setLayout(panelInternationalLayout);
        panelInternationalLayout.setHorizontalGroup(
            panelInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternationalLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelInternationalLayout.createSequentialGroup()
                            .addComponent(radioOneWay1)
                            .addGap(91, 91, 91)
                            .addComponent(radioRoundTrip1)
                            .addGap(87, 87, 87)
                            .addComponent(radioMultiCity1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInternationalLayout.createSequentialGroup()
                            .addGroup(panelInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelInternationalLayout.createSequentialGroup()
                                    .addComponent(lblFrom1)
                                    .addGap(280, 280, 280)
                                    .addComponent(lblTo1))
                                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelInternationalLayout.createSequentialGroup()
                                    .addGroup(panelInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfieldDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblDeparture1))
                                    .addGap(36, 36, 36)
                                    .addGroup(panelInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblReturn1)
                                        .addComponent(tfieldDate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(76, 76, 76)
                                    .addGroup(panelInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblAdults2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfieldAdults1)))
                                .addComponent(lblClass1)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelInternationalLayout.createSequentialGroup()
                                    .addComponent(lblSearchFlight1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(lblFlight_Hotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(55, 55, 55))
                        .addGroup(panelInternationalLayout.createSequentialGroup()
                            .addComponent(tfieldFrom1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(135, 135, 135)
                            .addComponent(tfieldTo1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tfieldChilds1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblChild2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(panelInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblChild3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfieldsInfants1))
                .addGap(82, 82, 82))
        );
        panelInternationalLayout.setVerticalGroup(
            panelInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternationalLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioOneWay1)
                    .addComponent(radioRoundTrip1)
                    .addComponent(radioMultiCity1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFrom1)
                    .addComponent(lblTo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfieldFrom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldTo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDeparture1)
                        .addComponent(lblReturn1))
                    .addComponent(lblAdults2)
                    .addGroup(panelInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblChild2)
                        .addComponent(lblChild3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfieldDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldDate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldAdults1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldChilds1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfieldsInfants1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClass1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(panelInternationalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSearchFlight1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFlight_Hotel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        PanelTabbedD_I.addTab("International", panelInternational);

        javax.swing.GroupLayout panelFlightLayout = new javax.swing.GroupLayout(panelFlight);
        panelFlight.setLayout(panelFlightLayout);
        panelFlightLayout.setHorizontalGroup(
            panelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFlightLayout.createSequentialGroup()
                .addGroup(panelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFlightLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblFlightText, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFlightLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(PanelTabbedD_I, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(466, Short.MAX_VALUE))
        );
        panelFlightLayout.setVerticalGroup(
            panelFlightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFlightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFlightText, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTabbedD_I)
                .addGap(30, 30, 30))
        );

        PanelTabbedD_I.getAccessibleContext().setAccessibleName("Domestic");

        panelTabbed.addTab("Reserve Seat", panelFlight);

        panelHotel.setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(107, 185, 240));

        jTable1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Passenger Type", "Flight No", "Total Payment"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblFlight_Hotel2.setBackground(new java.awt.Color(246, 71, 71));
        lblFlight_Hotel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblFlight_Hotel2.setForeground(new java.awt.Color(255, 255, 255));
        lblFlight_Hotel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFlight_Hotel2.setText("Cancel Reservation");
        lblFlight_Hotel2.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblFlight_Hotel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblFlight_Hotel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelHotelLayout = new javax.swing.GroupLayout(panelHotel);
        panelHotel.setLayout(panelHotelLayout);
        panelHotelLayout.setHorizontalGroup(
            panelHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHotelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHotelLayout.setVerticalGroup(
            panelHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHotelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelTabbed.addTab("Cancel Reservation", panelHotel);

        panelBackground.add(panelTabbed, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 1290, 510));

        getContentPane().add(panelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioMultiCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMultiCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMultiCityActionPerformed

    private void tfieldFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldFromActionPerformed

    private void tfieldToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldToActionPerformed

    private void tfieldAdultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldAdultsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldAdultsActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void radioMultiCity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMultiCity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMultiCity1ActionPerformed

    private void tfieldFrom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldFrom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldFrom1ActionPerformed

    private void tfieldTo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldTo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldTo1ActionPerformed

    private void tfieldAdults1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfieldAdults1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfieldAdults1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PanelTabbedD_I;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAdults1;
    private javax.swing.JLabel lblAdults2;
    private javax.swing.JLabel lblCallNow;
    private javax.swing.JLabel lblChild;
    private javax.swing.JLabel lblChild1;
    private javax.swing.JLabel lblChild2;
    private javax.swing.JLabel lblChild3;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblClass1;
    private javax.swing.JLabel lblDeparture;
    private javax.swing.JLabel lblDeparture1;
    private javax.swing.JLabel lblFlightText;
    private javax.swing.JLabel lblFlight_Hotel;
    private javax.swing.JLabel lblFlight_Hotel1;
    private javax.swing.JLabel lblFlight_Hotel2;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblFrom1;
    private javax.swing.JLabel lblLoginImg;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoText;
    private javax.swing.JLabel lblReturn;
    private javax.swing.JLabel lblReturn1;
    private javax.swing.JLabel lblSearchFlight;
    private javax.swing.JLabel lblSearchFlight1;
    private javax.swing.JLabel lblTo;
    private javax.swing.JLabel lblTo1;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelDomestic;
    private javax.swing.JPanel panelFlight;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelHotel;
    private javax.swing.JPanel panelInternational;
    private javax.swing.JTabbedPane panelTabbed;
    private javax.swing.JRadioButton radioMultiCity;
    private javax.swing.JRadioButton radioMultiCity1;
    private javax.swing.JRadioButton radioOneWay;
    private javax.swing.JRadioButton radioOneWay1;
    private javax.swing.JRadioButton radioRoundTrip;
    private javax.swing.JRadioButton radioRoundTrip1;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JTextField tfieldAdults;
    private javax.swing.JTextField tfieldAdults1;
    private javax.swing.JTextField tfieldChilds;
    private javax.swing.JTextField tfieldChilds1;
    private javax.swing.JTextField tfieldDate;
    private javax.swing.JTextField tfieldDate1;
    private javax.swing.JTextField tfieldDate2;
    private javax.swing.JTextField tfieldDate3;
    private javax.swing.JTextField tfieldFrom;
    private javax.swing.JTextField tfieldFrom1;
    private javax.swing.JTextField tfieldTo;
    private javax.swing.JTextField tfieldTo1;
    private javax.swing.JTextField tfieldsInfants;
    private javax.swing.JTextField tfieldsInfants1;
    // End of variables declaration//GEN-END:variables
}
